In [1]:
import json
from collections import Counter

with open("meged3.json", "r", encoding="utf-8") as f:
    data = json.load(f)

counter = Counter(item["tv_form"] for item in data if item.get("tv_form"))

VALID_CLASSES = [tv for tv, count in counter.items() if count >= 20]

filtered_data = [
    item for item in data
    if item.get("tv_form") in VALID_CLASSES
]

print("Total after filtering:", len(filtered_data))
print("Remaining classes:", len(set(x["tv_form"] for x in filtered_data)))

Total after filtering: 3209
Remaining classes: 16

In [2]:
import json

with open("meged3.json", "r", encoding="utf-8") as f:
    data = json.load(f)

count_double = 0
count_total = 0

for item in data:
    text = item["text"].lower()

    if "өйткені" in text:
        count_total += 1

        if text.count("өйткені") > 1:
            count_double += 1

print("Total өйткені:", count_total)
print("Multiple өйткені:", count_double)

if count_total > 0:
    print("Percent:", round(count_double / count_total * 100, 2), "%")

Total өйткені: 227
Multiple өйткені: 28
Percent: 12.33 %

In [3]:
import json
from collections import Counter

with open("meged3.json", "r", encoding="utf-8") as f:
    data = json.load(f)

marker_counter = Counter()

for item in data:

    tv = item.get("tv_form", "")
    
    # интересующий нас tv form
    if "Tv =fin" in tv:

        for span in item.get("spans", []):
            if "MARKER" in span.get("labels", []):
                marker = span["text"].lower()
                marker_counter[marker] += 1

print("Markers with Tv=fin structure:\n")

for marker, count in marker_counter.most_common():
    print(f"{marker:20} {count}")

Markers with Tv=fin structure:

өйткені              226
себебі               201
сондықтан            201
сол себепті          200
сол үшін             200
неге десең           193
 себебі              1

In [4]:
import json
from collections import defaultdict, Counter

with open("meged3.json", "r", encoding="utf-8") as f:
    data = json.load(f)

tv_marker_map = defaultdict(Counter)

for item in data:

    tv = item.get("tv_form", "UNKNOWN")

    for span in item.get("spans", []):
        if "MARKER" in span.get("labels", []):
            marker = span["text"].lower().strip()
            tv_marker_map[tv][marker] += 1


for tv, markers in tv_marker_map.items():

    print("\n======================================")
    print("TV FORM:", tv)
    print("--------------------------------------")

    for marker, count in markers.most_common():
        print(f"{marker:20} {count}")

======================================
TV FORM: Tv=ғандықтан, гендіктен, қандықтан, кендіктен
--------------------------------------
болғандықтан         49
дамығандықтан        6
өзгергендіктен       6
күшейгендіктен       6
қалыптасқандықтан    6
тұрақтанғандықтан    5
кеңейгендіктен       5
алғандықтан          4
тереңдегендіктен     4
отырғандықтан        3
асырылғандықтан      3
сақталғандықтан      3
нақтыланғандықтан    3
жаңарғандықтан       3
нығайғандықтан       3
бекітілгендіктен     3
білгендіктен         2
жүргізілгендіктен    2
білмегендіктен       2
болмағандықтан       2
қалғандықтан         2
алмағандықтан        2
берілгендіктен       2
зерттелмегендіктен   2
өткізгендіктен       2
жүйеленбегендіктен   2
қабылданғандықтан    2
дәлелденгендіктен    2
шиеленіскендіктен    2
ұшырағандықтан       2
реттелгендіктен      2
медиатизацияланғандықтан 2
жетілдірілгендіктен  2
қаралғандықтан       2
өскендіктен          2
жүйеленгендіктен     2
жаңғырғандықтан      2
қолданылғандықтан    2
жатқандықтан         2
бөлінбегендіктен     1
көргендіктен         1
сенгендіктен         1
ұсынылғандықтан      1
қамтығандықтан       1
аудармағандықтан     1
санағандықтан        1
жырланғандықтан      1
оқылғандықтан        1
түспегендіктен       1
бергендіктен         1
айналғандықтан       1
орнықпағандықтан     1
жасағандықтан        1
келмегендіктен       1
құрылғандықтан       1
цифрландырылмағандықтан 1
сақталмағандықтан    1
бейімделгендіктен    1
көшкендіктен         1
негізделгендіктен    1
жүргендіктен         1
эволюцияланғандықтан 1
жаңартылғандықтан    1
кеңейтілгендіктен    1
баяулағандықтан      1
байығандықтан        1
цифрланғандықтан     1
анықталғандықтан     1
модернизацияланғандықтан 1
бағаланғандықтан     1
трансформацияланғандықтан 1
орныққандықтан       1
таралғандықтан       1
жетілгендіктен       1
институционалданғандықтан 1
жасалғандықтан       1
еткендіктен          1
табылғандықтан       1
енгізілгендіктен     1
әлсірегендіктен      1
аяқталғандықтан      1
енгендіктен          1

======================================
TV FORM: [(N1) Tv =fin] себебі [(N1) Vfin.]
--------------------------------------
себебі               202

======================================
TV FORM: Tv=атындықтан, етіндіктен, итіндіктен
--------------------------------------
негізделетіндіктен   43
сүйенетіндіктен      41
болатындықтан        25
бағытталатындықтан   15
асырылатындықтан     5
өтетіндіктен         5
бағынатындықтан      4
қорғалатындықтан     4
ұйымдастырылатындықтан 3
құрылатындықтан      3
жүргізілетіндіктен   3
ететіндіктен         2
отыратындықтан       2
сақталатындықтан     2
қалыптасатындықтан   2
институционалданатындықтан 2
беретіндіктен        2
күрделенетіндіктен   2
табылатындықтан      1
кеңейетіндіктен      1
қайталанатындықтан   1
дамымайтындықтан     1
таралатындықтан      1
тарайтындықтан       1
ұштасатындықтан      1
жинақталатындықтан   1
келетіндіктен        1
қолданылатындықтан   1
тұрақтанатындықтан   1
айқындалатындықтан   1
регламенттелетіндіктен 1
ратификацияланатындықтан 1
анықталатындықтан    1
зерттелетіндіктен    1
бекітілетіндіктен    1
басталатындықтан     1
түсіндіретіндіктен   1
талданатындықтан     1
жинақтайтындықтан    1
ұсынатындықтан       1
тарататындықтан      1
әрекеттесетіндіктен  1
ұмтылатындықтан      1

======================================
TV FORM: Tv=атындықтан, етіндіктен, йтіндіктен, йтындықтан, итіндіктен
--------------------------------------
негізделетіндіктен   6
сүйенетіндіктен      2
саналатындықтан      1
етілетіндіктен       1
отыратындықтан       1
өтетіндіктен         1

======================================
TV FORM: Tv=атындықтан, етіндіктен, йтіндіктен, итіндіктен
--------------------------------------
қабылданатындықтан   1

======================================
TV FORM: Tv=ған=//=на, ген=//=не, қан=//=на, кен=//=не
--------------------------------------
әлсірегеніне         10
төмендегеніне        9
сақталмағанына       9
тоқтатылғанына       9
бұзылғанына          8
жарияланбағанына     8
баяулағанына         7
расталмағанына       7
бұрмаланғанына       7
ескерілмегеніне      6
күшейгеніне          5
жұмсалғанына         5
өзгертілгеніне       5
жарияланғанына       5
құлдырағанына        5
созылғанына          5
бағаланбағанына      5
өзгергеніне          5
қысқартылғанына      5
аяқталмағанына       4
азайғанына           4
нашарлағанына        4
жаңартылмағанына     4
өтпегеніне           3
орындалмағанына      3
қалыптасқанына       3
кешіктірілгеніне     2
асқанына             2
тереңдегеніне        2
жоғалғанына          2
поляризацияланғанына 2
қабылданбағанына     2
өткізілмегеніне      2
аяқталғанына         2
анықталғанына        2
есептелгеніне        2
жетпегеніне          2
келмегеніне          2
түсіндірілгеніне     2
қаралмағанына        2
қаралғанына          2
жүргізілмегеніне     2
бекітілмегеніне      1
қабылданғанына       1
қалғанына            1
берілгеніне          1
өткізілгеніне        1
ұсынылмағанына       1
қайталанбағанына     1
айырылғанына         1
дәлелденбегеніне     1
қаржыландырылмағанына 1
өткеніне             1
верификацияланбағанына 1
ашылмағанына         1
жеткеніне            1
қолданылғанына       1
алғанына             1
алынбағанына         1
сақталғанына         1
екеніне              1
жиналғанына          1
бекітілгеніне        1
жазылғанына          1
енгізілгеніне        1

======================================
TV FORM: Tv=атын//на, етін//не, йтін//не, йтын//на, итін//не
--------------------------------------
әлсірейтініне        14
болатынына           8
аспайтынына          8
баяулайтынына        6
қаралатынына         6
күшейтілетініне      6
төмендейтініне       5
өзгертілетініне      5
қысқартылатынына     5
верификацияланбайтынына 5
бағаланбайтынына     5
жаңартылмайтынына    5
тереңдетілетініне    5
келетініне           5
кеңейетініне         5
артатынына           5
жетілдірілетініне    5
дәлелденбейтініне    4
мойындалмайтынына    4
ескерілмейтініне     4
біріздендірілетініне 4
түсіндірілетініне    3
күшейетініне         3
орындалмайтынына     3
төмендейетініне      3
шектелетініне        3
енбейтініне          3
тереңдетілмейтініне  3
танылатынына         3
жанданатынына        3
біріздендірілмейтініне 2
нашарлайтынына       2
бұзылатынына         2
жарияланбайтынына    2
сақталмайтынына      2
созылатынына         2
жарияланатынына      2
радикалданатынына    2
жүргізілмейтініне    2
жеткізілетініне      2
қолданылмайтынына    2
расталмайтынына      2
ушығатынына          2
алатынына            2
тұрақсызданатынына   1
өзгеретініне         1
тереңдейетініне      1
теңеспейтініне       1
поляризацияланатынына 1
қаржыландырылмайтынына 1
бөлінетініне         1
өтетініне            1
ескерілетініне       1
бөлінбейтініне       1
артпайтынына         1
жеткізілмейтініне    1
аяқталмайтынына      1
игерілмейтініне      1
кеңеймейтініне       1
цифрланатынына       1
толықтырылатынына    1
тұрақтанатынына      1
келтірілетініне      1
енгізілетініне       1
кеңейтілетініне      1
аударылатынына       1
қаржыландырылатынына 1

======================================
TV FORM: Tv=ған//нан, ген//нен, қан//нан, кен//нен
--------------------------------------
өтпегенінен          13
ескерілмегенінен     10
аспағанынан          10
сақталмағанынан      8
алғанынан            7
әлсірегенінен        6
төмендегенінен       5
расталмағанынан      5
жаңартылмағанынан    5
орындалмағанынан     5
жүргізілмегенінен    5
болғанынан           5
жарияланбағанынан    4
тоқтатылғанынан      4
созылғанынан         4
бұзылғанынан         4
өзгертілгенінен      4
аяқталмағанынан      4
бағаланбағанынан     4
жұмсалғанынан        3
баяулағанынан        3
өзгергенінен         3
қалыптасқанынан      3
келмегенінен         3
жойылмағанынан       3
нығайтылмағанынан    3
жүргізілгенінен      3
болмағанынан         3
азайғанынан          2
нашарлағанынан       2
бұрмаланғанынан      2
дәлелденбегенінен    2
қысқартылғанынан     2
негізделмегенінен    2
ашылмағанынан        2
қаржыландырылмағанынан 2
қолданылғанынан      2
жарияланғанынан      2
күшейгенінен         2
ауытқығанынан        2
қалғанынан           2
ұсынылмағанынан      2
қысқарғанынан        2
бекітілмегенінен     2
қаралғанынан         2
сәйкестендірілмегенінен 2
аяқталғанынан        1
кешіктірілгенінен    1
тереңдегенінен       1
жоғалғанынан         1
қайталанбағанынан    1
поляризацияланғанынан 1
есептелгенінен       1
өткізілмегенінен     1
құлдырағанынан       1
талқыланбағанынан    1
қағылғанынан         1
келгенінен           1
түсіндірілмегенінен  1
қолданылмағанынан    1
зерттелмегенінен     1
бағытталмағанынан    1
баяндалмағанынан     1
танылмағанынан       1
пайдаланылмағанынан  1
бейімделмегенінен    1
дамымағанынан        1
сақталғанынан        1
түзетілмегенінен     1
енбегенінен          1

======================================
TV FORM: Tv=п, е, й
--------------------------------------
отырып               90
келе                 85
кодтап               5
талдай               2
кодтай               1

======================================
TV FORM: Tv=май, мей, бай, бей, пей
--------------------------------------
өтпей                20
бағаланбай           18
тексерілмей          15
талданбай            13
зерттелмей           10
жүйеленбей           10
салыстырылмай        10
сәйкестендірілмей    8
жүргізілмей          7
өткізілмей           7
сарапталмай          6
салыстырмай          5
жаңартылмай          5
орындалмай           5
ратификацияланбай    5
сақталмай            5
нығайтылмай          5
аяқталмай            5
негізделмей          5
дәлелденбей          4
интерпретацияланбай  3
айқындалмай          3
цифрландырылмай      3
регламенттелмей      3
бейімделмей          3
келісілмей           3
түсіндірілмей        2
жетілдірілмей        2
бекітілмей           2
тергелмей            2
жинақталмай          2
үйлестірілмей        2
жарияланбай          2
көшірілмей           2
қаржыландырылмай     1
нақтыланбай          1
қаралмай             1
реттелмей            1
рецензияланбай       1
алынбай              1
валидацияланбай      1
ұйымдастырылмай      1
расталмай            1
модельденбей         1
қалыптастырылмай     1

======================================
TV FORM: Tv=ған соң, ген соң, қан соң, кен соң
--------------------------------------
аяқталған соң        24
өткен соң            13
бекітілген соң       12
асқан соң            11
жасалған соң         8
жүргізілген соң      7
дәлелденген соң      7
енген соң            6
қабылданған соң      6
орындалған соң       6
енгізілген соң       6
қаралған соң         6
жарияланған соң      5
қорытындыланған соң  5
жүйеленген соң       5
жаңартылған соң      4
нақтыланған соң      4
анықталған соң       3
тексерілген соң      3
ұзартылған соң       3
талданған соң        3
жеткізілген соң      3
реттелген соң        3
жаңғыртылған соң     3
шыққан соң           2
тіркелген соң        2
қаржыландырылған соң 2
қосылған соң         2
өткізілген соң       2
берілген соң         2
толтырылған соң      2
қозғалған соң        2
орнаған соң          2
қабылдаған соң       2
өңделген соң         2
бағаланған соң       2
жіберілген соң       2
цифрландырылған соң  2
ратификацияланған соң 2
сәйкестендірілген соң 2
айқындалған соң      2
алынған соң          1
қайталанған соң      1
бұзылған соң         1
қорғалған соң        1
рәсімделген соң      1
зерттелген соң       1
нәтижеленген соң     1
есептелген соң       1
салыстырылған соң    1
қалыптастырылған соң 1

======================================
TV FORM: Tv=ғаннан кейін, геннен кейін, қаннан кейін, кеннен кейін
--------------------------------------
аяқталғаннан кейін   18
өңделгеннен кейін    16
алынғаннан кейін     15
тексерілгеннен кейін 15
жүргізілгеннен кейін 12
анықталғаннан кейін  10
талданғаннан кейін   10
жүйеленгеннен кейін  10
салыстырылғаннан кейін 9
жасалғаннан кейін    8
құрылғаннан кейін    8
сараланғаннан кейін  7
нақтыланғаннан кейін 7
жиналғаннан кейін    6
қалыптасқаннан кейін 6
жинақталғаннан кейін 6
белгіленгеннен кейін 5
ұсынылғаннан кейін   5
іріктелгеннен кейін  4
таңдалғаннан кейін   4
бекітілгеннен кейін  3
көшірілгеннен кейін  2
айқындалғаннан кейін 2
сұрыпталғаннан кейін 2
қарастырылғаннан кейін 2
қолданылғаннан кейін 2
интерпретацияланғаннан кейін 2
құрылымдалғаннан кейін 2
зерттелгеннен кейін  1
қамтылғаннан кейін   1

======================================
TV FORM: Tv=ғаны үшін, гені үшін, кені үшін, қаны үшін
--------------------------------------
бұзғаны үшін         52
орындамағаны үшін    49
сақтамағаны үшін     32
пайдаланғаны үшін    14
бұрмалағаны үшін     11
жасағаны үшін        6
жалтарғаны үшін      5
келмегені үшін       5
тапсырмағаны үшін    5
жұмсағаны үшін       4
еткені үшін          4
атқарғаны үшін       4
таратқаны үшін       2
ұсынғаны үшін        2
жариялағаны үшін     1
жасырғаны үшін       1
бергені үшін         1
кешіктіргені үшін    1
көрсеткені үшін      1

======================================
TV FORM: [(N1) Tv =fin] өйткені, өйткені де [(N1) Vfin.]
--------------------------------------
өйткені              1

======================================
TV FORM: [(N1) Tv =fin] өйткені [(N1) Vfin.]
--------------------------------------
өйткені              225

======================================
TV FORM: [(N1) Tv =fin] сондықтан [(N1) Vfin.]
--------------------------------------
сондықтан            201

======================================
TV FORM: [(N1) Tv =fin] сол себепті [(N1) Vfin.]
--------------------------------------
сол себепті          200

======================================
TV FORM: [(N1) Tv =fin] сол үшін [(N1) Vfin.]
--------------------------------------
сол үшін             200

======================================
TV FORM: [(N1) Tv =fin] неге десең, неге десеңіз [(N1) Vfin.]
--------------------------------------
неге десең           193

In [5]:
from sklearn.preprocessing import LabelEncoder

texts = [x["text"] for x in filtered_data]
labels = [x["tv_form"] for x in filtered_data]

label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

num_labels = len(label_encoder.classes_)
print("Number of classes:", num_labels)
print("Classes:", list(label_encoder.classes_))

id2label = {i: label for i, label in enumerate(label_encoder.classes_)}
label2id = {label: i for i, label in enumerate(label_encoder.classes_)}

Number of classes: 16
Classes: [np.str_('Tv=атын//на, етін//не, йтін//не, йтын//на, итін//не'), np.str_('Tv=атындықтан, етіндіктен, итіндіктен'), np.str_('Tv=май, мей, бай, бей, пей'), np.str_('Tv=п, е, й'), np.str_('Tv=ған соң, ген соң, қан соң, кен соң'), np.str_('Tv=ған//нан, ген//нен, қан//нан, кен//нен'), np.str_('Tv=ған=//=на, ген=//=не, қан=//=на, кен=//=не'), np.str_('Tv=ғандықтан, гендіктен, қандықтан, кендіктен'), np.str_('Tv=ғаннан кейін, геннен кейін, қаннан кейін, кеннен кейін'), np.str_('Tv=ғаны үшін, гені үшін, кені үшін, қаны үшін'), np.str_('[(N1) Tv =fin] неге десең, неге десеңіз [(N1) Vfin.]'), np.str_('[(N1) Tv =fin] себебі [(N1) Vfin.]'), np.str_('[(N1) Tv =fin] сол себепті [(N1) Vfin.]'), np.str_('[(N1) Tv =fin] сол үшін [(N1) Vfin.]'), np.str_('[(N1) Tv =fin] сондықтан [(N1) Vfin.]'), np.str_('[(N1) Tv =fin] өйткені [(N1) Vfin.]')]

In [6]:
from sklearn.model_selection import train_test_split
from datasets import Dataset

train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts,
    encoded_labels,
    test_size=0.2,
    random_state=42,
    stratify=encoded_labels
)

train_dataset = Dataset.from_dict({
    "text": train_texts,
    "labels": train_labels
})

test_dataset = Dataset.from_dict({
    "text": test_texts,
    "labels": test_labels
})

c:\Users\egisb\voice1\kazFineTune\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

CUDA available: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU

In [8]:
from transformers import AutoTokenizer

model_ckpt = "Eraly-ml/KazBERT"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

Map: 100%|██████████| 2567/2567 [00:00<00:00, 10262.74 examples/s]
Map: 100%|██████████| 642/642 [00:00<00:00, 14244.08 examples/s]

In [9]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_ckpt,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at Eraly-ml/KazBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [10]:
import numpy as np
from sklearn.metrics import f1_score, accuracy_score

def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    labels = p.label_ids

    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro")
    }

In [11]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./kazbert_tvform_final",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=8,
    weight_decay=0.01,
    fp16=True,
    load_best_model_at_end=True,
    logging_dir="./logs"
)

In [ ]:
# чтобы проверить другие модели
# from transformers import TrainingArguments

# training_args = TrainingArguments(
#     output_dir="./temp_output",   
#     eval_strategy="epoch",
#     save_strategy="no",         
#     learning_rate=2e-5,
#     per_device_train_batch_size=16,
#     per_device_eval_batch_size=16,
#     num_train_epochs=8,
#     weight_decay=0.01,
#     fp16=True,
#     load_best_model_at_end=False,  
#     logging_dir="./logs",
#     seed=42
# )

In [ ]:
# import torch
# import numpy as np
# import random

# torch.manual_seed(42)
# np.random.seed(42)
# random.seed(42)

In [12]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

C:\Users\egisb\AppData\Local\Temp\ipykernel_4708\4223154140.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=1288, training_loss=0.19346267160791789, metrics={'train_runtime': 2234.308, 'train_samples_per_second': 9.191, 'train_steps_per_second': 0.576, 'total_flos': 1350981955780608.0, 'train_loss': 0.19346267160791789, 'epoch': 8.0})

In [13]:
results = trainer.evaluate()
print(results)

{'eval_loss': 0.007966133765876293, 'eval_accuracy': 0.9984423676012462, 'eval_macro_f1': 0.9985261478707171, 'eval_runtime': 1.6471, 'eval_samples_per_second': 389.775, 'eval_steps_per_second': 24.892, 'epoch': 8.0}

In [14]:
from sklearn.metrics import classification_report

predictions = trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

print(classification_report(
    test_labels,
    preds,
    target_names=label_encoder.classes_
))

                                                           precision    recall  f1-score   support

      Tv=атын//на, етін//не, йтін//не, йтын//на, итін//не       1.00      1.00      1.00        39
                    Tv=атындықтан, етіндіктен, итіндіктен       1.00      1.00      1.00        38
                               Tv=май, мей, бай, бей, пей       1.00      1.00      1.00        43
                                               Tv=п, е, й       1.00      1.00      1.00        37
                    Tv=ған соң, ген соң, қан соң, кен соң       1.00      1.00      1.00        40
                Tv=ған//нан, ген//нен, қан//нан, кен//нен       1.00      1.00      1.00        40
            Tv=ған=//=на, ген=//=не, қан=//=на, кен=//=не       1.00      1.00      1.00        41
            Tv=ғандықтан, гендіктен, қандықтан, кендіктен       0.98      1.00      0.99        40
Tv=ғаннан кейін, геннен кейін, қаннан кейін, кеннен кейін       1.00      1.00      1.00        40
            Tv=ғаны үшін, гені үшін, кені үшін, қаны үшін       1.00      1.00      1.00        40
     [(N1) Tv =fin] неге десең, неге десеңіз [(N1) Vfin.]       1.00      1.00      1.00        39
                       [(N1) Tv =fin] себебі [(N1) Vfin.]       1.00      1.00      1.00        40
                  [(N1) Tv =fin] сол себепті [(N1) Vfin.]       1.00      1.00      1.00        40
                     [(N1) Tv =fin] сол үшін [(N1) Vfin.]       1.00      1.00      1.00        40
                    [(N1) Tv =fin] сондықтан [(N1) Vfin.]       1.00      1.00      1.00        40
                      [(N1) Tv =fin] өйткені [(N1) Vfin.]       1.00      0.98      0.99        45

                                                 accuracy                           1.00       642
                                                macro avg       1.00      1.00      1.00       642
                                             weighted avg       1.00      1.00      1.00       642

In [15]:
trainer.save_model("kazbert_tvform_model_final")
tokenizer.save_pretrained("kazbert_tvform_model_final")

('kazbert_tvform_model_final\\tokenizer_config.json',
 'kazbert_tvform_model_final\\special_tokens_map.json',
 'kazbert_tvform_model_final\\vocab.txt',
 'kazbert_tvform_model_final\\added_tokens.json',
 'kazbert_tvform_model_final\\tokenizer.json')

In [16]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_dir = "kazbert_tvform_model_final"

tokenizer = AutoTokenizer.from_pretrained(model_dir)
model = AutoModelForSequenceClassification.from_pretrained(model_dir)

tv_pipeline = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer
)

Device set to use cuda:0

In [17]:
sentence = "Қысқа да әрі нақты, көпке түсінікті болғандықтан студенттерге бір деммен оқу қиынға соқпауы мүмкін."
prediction = tv_pipeline(sentence)

print(prediction)

[{'label': 'Tv=ғандықтан, гендіктен, қандықтан, кендіктен', 'score': 0.9955139756202698}]

In [ ]:
# def train_sequence_model(model_ckpt, task_name):

#     tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

#     model = AutoModelForSequenceClassification.from_pretrained(
#         model_ckpt,
#         num_labels=num_labels,
#         id2label=id2label,
#         label2id=label2id
#     )

#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=train_dataset,
#         eval_dataset=test_dataset,
#         tokenizer=tokenizer,
#         compute_metrics=compute_metrics
#     )

#     trainer.train()

#     results = trainer.evaluate()

#     print(f"\n===== {task_name} =====")
#     print(results)

#     return results

In [ ]:
# from transformers import Trainer

# results_kazbert = train_sequence_model("Eraly-ml/KazBERT", "KazBERT")
# results_xlmr = train_sequence_model("xlm-roberta-base", "XLM-R")
# results_mbert = train_sequence_model("bert-base-multilingual-cased", "mBERT")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at Eraly-ml/KazBERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\egisb\AppData\Local\Temp\ipykernel_28532\2004852314.py:12: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

===== KazBERT =====
{'eval_loss': 0.019424259662628174, 'eval_accuracy': 0.9963898916967509, 'eval_macro_f1': 0.9964280133056505, 'eval_runtime': 0.4595, 'eval_samples_per_second': 602.854, 'eval_steps_per_second': 39.175, 'epoch': 8.0}

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\egisb\AppData\Local\Temp\ipykernel_28532\2004852314.py:12: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

===== XLM-R =====
{'eval_loss': 0.21768327057361603, 'eval_accuracy': 0.9422382671480144, 'eval_macro_f1': 0.9425685425685426, 'eval_runtime': 0.4573, 'eval_samples_per_second': 605.727, 'eval_steps_per_second': 39.361, 'epoch': 8.0}

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-multilingual-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 72f057d1-7d87-4834-912f-b7d2b9c8ef3b)')' thrown while requesting HEAD https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\egisb\AppData\Local\Temp\ipykernel_28532\2004852314.py:12: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

===== mBERT =====
{'eval_loss': 0.14251770079135895, 'eval_accuracy': 0.9458483754512635, 'eval_macro_f1': 0.9462090413527264, 'eval_runtime': 0.9224, 'eval_samples_per_second': 300.301, 'eval_steps_per_second': 19.514, 'epoch': 8.0}